[algokit]
min_version = "v2.0.0"

[project]
type = "sdk"
name = 'use-wallet-ui'

[project.run]
build = { commands = ['env NODE_OPTIONS="--max-old-space-size=4096" pnpm run build'], description = 'Build use-wallet-ui' }
build2 = { commands = ['env NODE_OPTIONS="--max-old-space-size=4096" pnpm run build'], description = 'Build use-wallet-ui' }
